### PR TITLE
Babelify

### PR DESCRIPTION
**Pull request by millern**

### CODE REVIEW

**Comment by guilload** [comment]
As a JS newbie I didn't know about ES2015. I've read the specs and... wow! Looks like Javascript is becoming a real language ;)

**Comment by ramdog** [comment]
Did you see this from running `grunt-serve`?

```
Running "express:dev" (express) task
Starting background Express server
debugger listening on port 5858
js-bson: Failed to load c++ bson extension, using pure JS version

Running "wait" task
>> Waiting for server reload...
Wiping out database
Express server listening on 9000, in development mode

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/ramintaleghani/Documents/Projects/thrashtown/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/Users/ramintaleghani/Documents/Projects/thrashtown/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/ramintaleghani/Documents/Projects/thrashtown/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
```

**Comment by ramdog** [comment]
Awesome work!  Stoked to learn ES6.

:+1:

**Comment by guilload** [comment]
So it's working?

**Pull request merged**
